spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3:4b
        options:
          temperature: 0.7
          top-p: 0.9
  servlet:
    multipart:
      enabled: true
      max-file-size: 64MB
      max-request-size: 65MB
      file-size-threshold: 1MB

  file:
    upload-dir: ./uploads
